### Site Settings ###
title               : Deep Heteroscedastic Regression
description         : |
                      Deep Heteroscedastic Regression: Methods and Applications <br><br>
                      We study different methods and applications of heteroscedastic regression across machine learning and computer vision. Our research is published in top venues such as ICML and ICLR. <br><br>
                      Megh Shukla, Mathieu Salzmann, Alexandre Alahi
                      École Polytechnique Fédérale de Lausanne (EPFL) <br><br>


baseurl             : ""                                # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : deep-regression/deep-regression.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : True                             # Opens external URLs in new tab (works for posts, projects and navbar only)
landing_vertical    : False                             # Set the front page to be vertical (true) or horizontal (false)

### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Megh Shukla
  image             : https://raw.githubusercontent.com/deep-regression/deep-regression.github.io/master/files/deep-regression.png
# behance           : your_username
# dribbble          : your_username
  email             : work.meghshukla@gmail.com
# facebook          : your_username
  github            : meghshukla
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : meghshukla
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : meghshukla
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /posts/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

  CV:
    output: true
    permalink: /CV/:name


### Disqus ###
# disqus:
#   shortname: meghshukla                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
  - scope:
      path: ""
      type: "CV"
    values:
      layout: "page"
  #  values:
  #    comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
